# This file was generated by update.sh

{
  "kicad" = {
    kicadVersion = {
      version =			"8.0.6";
      src = {
        rev =			"16c59e4e71dab2a0ed2f9e61f990b69657b4bfe2";
        sha256 =		"1vc9igk8id2c34shilg7lh361psvwiqxpsn2yq7cwnwgaq7v1swq";
      };
    };
    libVersion = {
      version =			"8.0.6";
      libSources = {
        symbols.rev =		"5fab56fc44319fed1d159cd7fa48e4468b0a5dad";
        symbols.sha256 =	"1ahzx14bmjgpvifsl2xm8c76zagkj2spc9cpb8ms4jlda92lp078";
        templates.rev =		"2343281a4df1ffbd4e0c6fcb9856f81adbbc201e";
        templates.sha256 =	"03idwrk3vj9h2az8j8lqpbdbnfxdbkzh4db68kq3644yj3cnlcza";
        footprints.rev =	"2e76906e448f352228a8f6bc06f77ae959a57975";
        footprints.sha256 =	"1fv0liwbl2blwd2xy9whwinkczi98ah83rwi4v6bvm9d9318vbig";
        packages3d.rev =	"005244f418b0d014e2907ca42df5ab85a1e29466";
        packages3d.sha256 =	"1i6ypl7lw7hnifl943z3lwv4sy00mfwgqi001bj9qh547kf9rxd4";
      };
    };
  };
  "kicad-testing" = {
    kicadVersion = {
      version =			"8.0-2024-02-23";
      src = {
        rev =			"14d71c8ca6b48d2eb956bb069acf05a37b1b2652";
        sha256 =		"0xqd0xbpnvsvba75526nwgzr8l2cfxy99sjmg13sjxfx7rq16kqi";
      };
    };
    libVersion = {
      version =			"8.0-2024-02-23";
      libSources = {
        symbols.rev =		"e228d4e8b295364e90e36c57f4023d8285ba88cd";
        symbols.sha256 =	"049h2a7yn6ks8sybppixa872dbvyd0rwf9r6nixvdg6d13fl6rwf";
        templates.rev =		"2e00c233b67e35323f90d04c190bf70237a252f2";
        templates.sha256 =	"0m9bggz3cm27kqpjjwxy19mqzk0c69bywcjkqcni7kafr21c6k4z";
        footprints.rev =	"6e5329a6d4aaa81290e23af3eba88f505c2f61b0";
        footprints.sha256 =	"0ypjlbmzmcl3pha3q2361va70c988b1drxy8320gm66jkzfc21a1";
        packages3d.rev =	"d1e521228d9f5888836b1a6a35fb05fb925456fa";
        packages3d.sha256 =	"0lcy1av7ixg1f7arflk50jllpc1749sfvf3h62hkxsz97wkr97xj";
      };
    };
  };
  "kicad-unstable" = {
    kicadVersion = {
      version =			"2024-09-09";
      src = {
        rev =			"59575c19d87b6bc01344844bcab4ac1718585b7c";
        sha256 =		"sha256-ahKL56wJUxwH6rAbhmNwXNKGWA0mqcdpa9W7mBpjgjY=";
      };
    };
    libVersion = {
      version =			"2024-09-09";
      libSources = {
        symbols.rev =		"f34ca0fe4d703626a2e548d587ebcb49dbf1cf6a";
        symbols.sha256 =	"sha256-zv7aZWMeiy/NiqpsxnitPp1GR93DPpo7uFSt5xB5aIs=";
        templates.rev =		"b65257c57a6222d67db23a6d2b205600e3bf4c9a";
        templates.sha256 =	"sha256-6jNq2ZCeEDPwRGY1Av9crTu72rqYIom+EjDJPWbmLQ4=";
        footprints.rev =	"70c89e2a017e52de1a86c23a6c6799da232d3033";
        footprints.sha256 =	"sha256-3N6cyDyYQrBcbBfjIfnXSpD6xQTDBY/6nkdMN/Ty4Hg=";
        packages3d.rev =	"eef24e75adc1d7a09e987b00fee9967b29aedd2e";
        packages3d.sha256 =	"sha256-UVVggKKvHIkkiZdKTdvYW3tCC5nzSgtW5qB/MzZm0Q8=";
      };
    };
  };
}
